[tool.isort]
profile = "black"
line_length = 120
skip_gitignore = true
known_first_party = ["users", "quiz", "pickmequiz"]
src_paths = ["users", "quiz", "pickmequiz"]
skip = ["migrations", "venv", "env", ".venv"]